name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      NONINTERACTIVE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpan -T Test::Pod Test::Pod::Coverage Pod::Coverage::TrustPod Test::Kwalitee BSD::Resource Import::Into File::Temp IPC::System::Simple
      - name: prove tests
        run: prove -wl t/*.t
